[msg MSG_preDartsStart_Moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]All right, let's get this team game underway.[n][f 1 3 65535][w][e]

[sel SEL_NextPlayOrder_Ans top]
[s]Let's do it.[e]
[s]How're things with [var 0]...[e]
[s]I'm calling it a day.[e]

[sel SEL_PlayCourse_Ans top]
[s]Let's play 301.[e]
[s]I'm thinking 501.[e]
[s]We're doing 701.[e]

[msg MND_DartsHeroBatonInfo]
[s][vp 8 2 0 0 65535 0]I feel like I've learned something[n]by playing on a team...[n][f 1 3 65535][w][e]

[msg MSG_DartsEnd_Moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1126 65535 0]We can train up, and have fun at the[n]same time. This is a pretty handy place.[n][f 1 3 65535][w][e]

[msg SYS_FinishInfo]
[s]If there is only a small amount of your score[n]remaining by round 4, your teammate may ask[n]for advice on how they should throw.[n][w][e]
[s]There is a higher chance of them finishing the[n]game if you give an answer that motivates them.[n][w][e]
[s]When your teammate finishes in this way,[n]your synergy with that teammate increases,[n]leveling up your Baton Pass rank.[n][w][e]

[msg MSG_GameEnd_ChallengeBon [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53125 65535 0][f 4 22 65535 1 41]Whoa... That was some crazy skill![n][f 1 3 65535][w][e]

[msg MSG_GameEnd_ChallengeBon_2 [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0][f 4 22 65535 1 41]You played really well that game![n][f 1 3 65535][w][e]

[msg SYS_AwardInfo]
[s]Performing well, like pulling off a hat trick or high[n]ton, will increase your [stIcon 2][clr 26][stLabel 2][clr 27] at the[n]end of the darts game.[n][w][e]

[msg MSG_AwardInfo_moru [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Seems like there's a lot of different[n]awards in this case. Hehe, I did[n]my homework![n][f 1 3 65535][w][e]

[msg MSG_Minigame_Kiyou [Morgana]]
[s][bup 0 3 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 1020 65535 0][f 4 22 65535 1 41]Tired from all that precise throwing?[n]I can tell you've grown somewhat[n]though.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7103 65535 0]Alright, let's go first![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]Yo, yo! I wanna go next![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_ryuji [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7192 65535 0]Man, ending on this note would suck,[n]don't you think? C'mon, let's do one[n]more![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_ryuji [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7063 65535 0]Aww... That's no fun.[n][f 1 3 65535][w][e]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Well, it's fine. We'll play next time![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's go with 301. Hehe, this'll be easy![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's go with 501. A little hard, but we[n]want a bit of a challenge, yeah?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm, what ruleset to go with...[n]Ya know what? I'll leave it up to you![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I hear ya! Then [var 0] it is.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7110 65535 0]Alright, let's do this! We're gonna get[n]0 points, right on the dot![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Guess I'm up... I'm goin' all out![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]On to round 3. Hehe, you got this man![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_ryuji [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7020 65535 0]Okay... This is my last round. Better not[n]screw this up, huh?[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7080 65535 0]For better or worse, this is the last round![n]It's all you![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_ryuj [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7155 65535 0]Oof... Hey, don't let it get to you dude.[n]I'll take it from here![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_ryuji [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7025 65535 0]Aw, crap... Sorry man, it's all up to you...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis [Ryuji]]
[s][bup 0 2 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 7027 65535 0]...Looks like I might be able to go for a[n]finish... Man, I'm getting so nervous![n][f 1 3 65535][w][e]

[sel SEL_Finish_ryuji top]
[s]You gotta psych yourself up![e]
[s]Just play naturally.[e]
[s]Don't think about anything.[e]

[msg MSG_Finish_Act01_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7186 65535 0]Heh, I get you! I'm goin' all in on this one![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_ryuji [Ryuji]]
[s][bup 0 2 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 7133 65535 0]You're right, I can't let myself stiffen[n]up... Guess I'll relax and take it easy[n]on this one.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_ryuji [Ryuji]]
[s][bup 0 2 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 7177 65535 0]O-Oh yeah? Don't think about[n]anything?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54214 65535 0]We did it! 0 points![n]Dude, aren't we just the greatest team!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Heh... Man, I feel so motivated right[n]now! Maybe 'cause I knew you were[n]countin' on me?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_r [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7023 65535 0]We did it! 0 points![n]Dude, aren't we just the greatest team!?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ry [Ryuji]]
[s][bup 0 2 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 7021 65535 0][var 0] left, huh? Argh, we almost[n]made it to 0...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad [Ryuji]]
[s][bup 0 2 7 65535 0][f 4 10 65535 0 0][vp 8 2 0 7114 65535 0]Still had [var 0] points left...[n]Man, this result kinda sucks.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54242 65535 0]Man, that was fun! Worked up a good[n]sweat there![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_ryuji [Ryuji]]
[s][vp 8 2 0 7062 65535 0]Welp, see ya![n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1051 65535 0][fName], let's team up for the first[n]game. Heh, time to show my stuff.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1067 65535 0]I'm up next! Lemme show you what[n]these paws can do![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_moru [Morgana]]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]This can't be right... One more try![n]You're not satisfied with this either,[n]are you?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1043 65535 0]...Huh? But I was all raring to go...[n][f 1 3 65535][w][e]
[s][bup 0 3 3 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Oh well, I'm sure you've got a lot to[n]think about. We'll play next time.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's go with 301. Should be a cinch if[n]we combine our strength![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's go with 501. Stay focused, or[n]you're in for a rude awakening.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Let's see, which ruleset should we use...?[n]I'll let you decide![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]All right! Then let's play [var 0].[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1156 65535 0]You ready to go? Let's give it all we got![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1117 65535 0]Looks like it's my turn next![n]Nyahaha, don't fall for me now.[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_moru [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1034 65535 0]So, now we're into round 3... We gotta[n]really pay attention to the score now![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1133 65535 0]So this is my last round...[n]Heh, this is starting to get interesting.[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]This is the last round! I know you'll[n]come through![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1027 65535 0]Er, don't worry about that! I'll take care[n]of this![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1112 65535 0]...S-Sorry! That was careless of me...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_2 [Morgana]]
[s][bup 0 3 4 0 0][f 4 10 65535 0 0][vp 8 2 0 1130 65535 0]Hmm... We have a chance to finish it[n]here. All right... here goes![n][f 1 3 65535][w][e]

[sel SEL_Finish_moru top]
[s]I need some cat-like reflexes.[e]
[s]Your hair's standing on end.[e]
[s]I'm counting on you.[e]

[msg MSG_Finish_Act01_moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1031 65535 0]Man, you sure got a way with words![n]I think I've got this now![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_moru [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1024 65535 0]Oh, all right... But they definitely aren't[n]cat-like, okay!?[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_moru [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0]O-Oh, right... Okay, see?[n]I... I'm calm meow...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_2 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1184 65535 0]A perfect 0! Nobody can beat us when[n]we're teamed up![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]It was because I could feel your[n]motivation. It made me able to try[n]harder than usual.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_m [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0]A perfect 0! Nobody can beat us when[n]we're teamed up![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_mo [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0][var 0] left... We almost had it...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_2 [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1044 65535 0][var 0] points left... That wasn't so great.[n]Sorry, I should've been doing better...[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_moru [Morgana]]
[s][vp 8 2 0 1049 65535 0]All right, let's head back.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 6019 65535 0]Ooh! [fName], let's you and me[n]get the first game![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6075 65535 0]I wanna go next! I'm itching to play![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_anne [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6021 65535 0]I don't want it to end like this...![n]Hey, can we play one more?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_anne [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6063 65535 0]Oh... Well, that's unfortunate.[n][f 1 3 65535][w][e]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I guess we'll just play some other time![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's do 301. I think I can handle that![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's do 501. Ehehe... I'll try not to[n]mess up.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm... What rules should we go with...[n]Sorry, would you mind deciding?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Got it! Then let's play [var 0]![n][f 1 3 65535][w][e]

[msg MSG_StartRound01_anne [Ann]]
[s][bup 0 4 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54043 65535 0]Good luck! I'm rooting for you![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_anne [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 54044 65535 0]Okay, I'm up next. Yikes, I'm getting[n]nervous![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6117 65535 0]It's round 3 now... Let's keep at it![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_anne [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6028 65535 0]This is my last round...[n]Gotta make sure I don't screw it up![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6185 65535 0]Last round! You can do this![n]I believe in you![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_anne [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6027 65535 0]Uh-oh... Did you overshoot there?[n]It's fine, don't let it get to you![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_anne [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6170 65535 0]...I-I'm sorry. I got a little carried away...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_3 [Ann]]
[s][bup 0 4 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 6039 65535 0]Oh... We can finish it right here![n]...I think I'm nervous.[n][f 1 3 65535][w][e]

[sel SEL_Finish_anne top]
[s]Finish it.[e]
[s]Is it getting hot in here?[e]
[s]Just play like normal.[e]

[msg MSG_Finish_Act01_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6060 65535 0]Oh, right! Yeah, that's all you can[n]really do![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6048 65535 0]What're you talking about!?[n]...Hehe, that actually helped me relax.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_anne [Ann]]
[s][bup 0 4 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 6190 65535 0]S-Sure. I got this.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_3 [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54042 65535 0]We did it! 0 points exactly![n]Do we make an awesome team or what?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I could feel you were counting on me...[n]So I had to try really hard![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_a [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54042 65535 0]We did it! 0 points exactly![n]Do we make an awesome team or what?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_an [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6038 65535 0][var 0] left, huh... Argh,[n]we almost had it![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_3 [Ann]]
[s][bup 0 4 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 6038 65535 0][var 0] points left...[n]Ahaha, that's not very good.[n]Sorry, this was pretty hard for me...[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54049 65535 0]Whew... That was nerve-racking,[n]but fun![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_anne [Ann]]
[s][vp 8 2 0 6053 65535 0]Well, see you around.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 1 4080 65535 0]Let us team up for the first match,[n][fName]. *chuckle* How exciting...![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4034 65535 0]All right, I shall go next.[n]Let us dance... with darts![n][f 1 3 65535][w][e]

[msg MSG_NextRetry_yusuke [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4033 65535 0]It seems this is no ordinary game...![n]Please, let me try again![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_yusuke [Yusuke]]
[s][bup 0 5 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 4064 65535 0]...I see. That is regrettable.[n][f 1 3 65535][w][e]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]However, it may be best not to be overeager.[n]The challenge can wait until another time![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let us go with 301. Everything starts[n]with the basics.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let us go with 501. I wish to give[n]myself a challenge...[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm, what ruleset should we use...?[n]My apologies, but I'll leave the decision[n]to you.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_yusuk [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Very well. We shall play [var 0] then.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4060 65535 0]And so it begins... There is no need[n]to get worked up; go with the natural[n]approach![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4048 65535 0]My turn... *chuckle*[n]I revel in this feeling of tension...![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4107 65535 0]It's round 3... Time certainly flies when[n]you're having fun...![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_yusuke [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4083 65535 0]This is a critical point for me.[n]Please carry on when I'm gone...![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4198 65535 0]The last round... I'll watch you until[n]your final moments, so finish strong![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_yusu [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4076 65535 0]I see... But this is what makes life so[n]interesting. Fear not, and let bygones[n]be bygones.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_yusuke [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4073 65535 0]This wasn't supposed to happen![n]How could I fail...? Forgive me.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_4 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4119 65535 0]We have the opportunity to finish it[n]here! Hrm... My hand is shaking...!?[n][f 1 3 65535][w][e]

[sel SEL_Finish_yusuke top]
[s]Pretend like you're painting.[e]
[s]Is it an earthquake?[e]
[s]It's shaking with excitement.[e]

[msg MSG_Finish_Act01_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4131 65535 0]You're right. Painting is about being in[n]the moment! Yes... I can do it now![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_yusuke [Yusuke]]
[s][bup 0 5 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 4134 65535 0]...You may be right. Heh.[n]The shaking has calmed somewhat.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_yusuke [Yusuke]]
[s][bup 0 5 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 4139 65535 0]What? But, the building isn't shaking...[n]No, it is only my fingers that tremble...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_4 [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4190 65535 0]A perfect 0... and a perfect success.[n]The goddess of victory has smiled[n]upon us![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]What a stimulating session of passion for[n]us both! I am in high spirits indeed![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_y [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4190 65535 0]A perfect 0... and a perfect success.[n]The goddess of victory has smiled[n]upon us![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_yu [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0][var 0] remaining... Ngh, we came[n]close. Were we just a little bit[n]short on our determination?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_4 [Yusuke]]
[s][bup 0 5 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 4047 65535 0][var 0] points remaining...[n]What an abysmal result. It seems I've[n]underestimated the intricacies of darts.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53736 65535 0]The sensation of throwing darts...[n]I don't dislike it.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_yusuke [Yusuke]]
[s][vp 8 2 0 4054 65535 0]Now then, farewell.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2019 65535 0]Hey, [fName], can we go first?[n]I'd like to test this technique I've[n]thought up.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2057 65535 0]Um... Could I go next? I've been studying[n]the theory on how to play darts.[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2129 65535 0]To be honest... I can't accept this result.[n]Do you think we could play one more[n]game?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2063 65535 0]...All right then.[n]That's a little disappointing.[n][f 1 3 65535][w][e]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]We'll play some other time. I'll be[n]running the simulations in my head[n]until then.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's try 301. It's best to[n]start with the basics, no?[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's try 501. The greater the challenge,[n]the greater the chance to grow.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hmm... Which ruleset should we use...?[n]Sorry, could I ask you to decide?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_makot [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]All right then. [var 0] it is.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2108 65535 0]Good luck. As long as you stay calm,[n]you should be fine![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_makoto [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2165 65535 0]It's my turn...![n]Now, if I just do it like the simulations...[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2114 65535 0]It's already round 3... Make sure to[n]stay focused![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_makoto [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2064 65535 0]So this is my last round... I need to[n]throw without overthinking things...![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2053 65535 0]You're our only hope now. Best of[n]luck on the final round![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_mako [Makoto]]
[s][bup 0 6 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 2199 65535 0]Looks like your hand slipped...[n]It's all right. Don't let it get to you.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2178 65535 0]Wh-What...!? How could this happen...?[n]I'm so sorry.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_5 [Makoto]]
[s][bup 0 6 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 2188 65535 0]Oh... We could finish it right here.[n]I-I have to remember the simulations...[n][f 1 3 65535][w][e]

[sel SEL_Finish_makoto top]
[s]What simulations?[e]
[s]Just take it easy.[e]
[s]Take a deep breath.[e]

[msg MSG_Finish_Act01_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2135 65535 0]Oh, right... Controlled breathing![n]Yes... I feel much calmer![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_makoto [Makoto]]
[s][bup 0 6 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 2165 65535 0]...You're right. I need to relax. Okay,[n]I'll give it my best shot.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_makoto [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2170 65535 0]Oh, umm... Do I... have to explain[n]that right now?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_5 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2162 65535 0]0 points! We did it![n]We make an excellent pair, don't we?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I see... The positive effects of synergy[n]between two people yield unexpectedly[n]strong results...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_m_2 [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2162 65535 0]0 points! We did it![n]We make an excellent pair, don't we?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ma [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2028 65535 0]We had [var 0] left... This is pretty difficult.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_5 [Makoto]]
[s][bup 0 6 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 2021 65535 0]We had [var 0] left... That's no good.[n]I'm sorry, I should have tried harder.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53335 65535 0]That was fun. I like gradually improving[n]my form with every throw.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_makoto [Makoto]]
[s][vp 8 2 0 2053 65535 0]See you later.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9155 65535 0]All right [fName], let's play![n]Hehehe... The gamer in me is raring[n]to go![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9055 65535 0]Yo! I call next! C'mon, can I go?[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_futaba [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9043 65535 0]I am strongly opposed to this result![n]Requesting a retry![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_futaba [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9040 65535 0]So it's come to this... So, it has come[n]to this...![n][f 1 3 65535][w][e]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Okay, fine. But we're comin' back[n]here sometime soon![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]It's gotta be 301. Three hundred and one![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules: it's gotta be 501.[n]It feels more satisfying to clear a[n]harder difficulty![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Hrrm... What rules to go with...[n]Okay, you pick![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_futab [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Affirmative! We're going with [var 0] then![n][f 1 3 65535][w][e]

[msg MSG_StartRound01_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9177 65535 0]Don't worry. Where there's a will,[n]there's a way![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9089 65535 0]Heh, I'm gonna nail this, no problem![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9076 65535 0]All warmed up now? You just gotta[n]go fwoosh and then bam![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_futaba [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 9189 65535 0]My last round... Th-Things are[n]getting interesting, as they say...![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54738 65535 0]Don't panic now! Just believe in[n]yourself and throw![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_futa [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54743 65535 0]Don't give up yet! Remember how[n]far you've come![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_futaba [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 54741 65535 0]I miscalculated...! Please forgive me...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_6 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9029 65535 0]This is my chance to finish it...[n]A-Am I actually getting nervous!?[n][f 1 3 65535][w][e]

[sel SEL_Finish_futaba top]
[s]The target is a pumpkin.[e]
[s]This is real.[e]
[s]Wanna switch?[e]

[msg MSG_Finish_Act01_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9135 65535 0]This feeling of tension... It's totally real![n]Yes! I'm gonna clutch it out![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_futaba [Futaba]]
[s][bup 0 8 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 9030 65535 0]Yo, we can't do that... Heh, you can[n]keep your pity![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_futaba [Futaba]]
[s][bup 0 8 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 9040 65535 0]Y-You make it sound so simple...[n]Besides, it looks more like a pizza![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_6 [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]Woohoo! 0 points! None can best us![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]We charged through the battlefield[n]together... I'll toast you with a soda later![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_f [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9105 65535 0]Woohoo! 0 points! None can best us![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_fu [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9043 65535 0][var 0] leftover...? We were so[n]close to finishing...![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_6 [Futaba]]
[s][bup 0 8 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 9043 65535 0][var 0] points leftover...?[n]This is depressing.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54737 65535 0]I feel like a ninja! This is fun![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_futaba [Futaba]]
[s][vp 8 2 0 9012 65535 0]Time to make like a tree![n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3057 65535 0]Um... [fName]-kun, would you[n]mind playing with me? I'd appreciate[n]it if you could show me what to do.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3057 65535 0]Okay... It's my turn next. Let's both do[n]our best.[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3110 65535 0]Hmm... Could we please play one more?[n]I don't want it to end this way![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_haru [Haru]]
[s][bup 0 7 3 65535 0][f 4 10 65535 0 0][vp 8 2 0 3047 65535 0]Oh... really?[n]Hmm... That's so unfortunate.[n][f 1 3 65535][w][e]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]But, oh well. Let's play some other[n]time though![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's go with 301. I can handle this...[n]I think.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Let's go with 501. I'm a little nervous,[n]but it should be fun, right?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Umm... What ruleset should we use...[n]I'm sorry, but could you decide for us?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Okay! We're going to play [var 0] then.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53522 65535 0]Good luck! The important thing is[n]to have fun![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53501 65535 0]Here I go! I'll do my best...![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]It's the third round! I've got a good[n]feeling about this![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_haru [Haru]]
[s][bup 0 7 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 3178 65535 0]So this is my last turn... I can do this![n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3119 65535 0]It's the final round! I'm so nervous...![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3118 65535 0]Don't worry about that, okay?[n]You almost had it![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3027 65535 0]Wha...? I'm sorry...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_7 [Haru]]
[s][bup 0 7 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 3180 65535 0]Look at our score... We can finish![n]How should I throw!?[n][f 1 3 65535][w][e]

[sel SEL_Finish_haru top]
[s]With elegance.[e]
[s]Like you're swinging an axe.[e]
[s]Have fun with it.[e]

[msg MSG_Finish_Act01_haru [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 53531 65535 0]...That's right! I feel kind of excited now![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_haru [Haru]]
[s][bup 0 7 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 3135 65535 0]Elegance...? Oh, you mean just throw[n]naturally! Okay, be myself... Be myself![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_haru [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3196 65535 0]Huh!? Does that have anything to do[n]with darts?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_7 [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3104 65535 0]Oh, look! 0 points! Wow...[n]I feel so accomplished![n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]We're the greatest pair ever... Maybe?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_h [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3104 65535 0]Oh, look! 0 points! Wow...[n]I feel so accomplished![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ha [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3028 65535 0][var 0] left... We didn't make it.[n]I wonder what went wrong...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_7 [Haru]]
[s][bup 0 7 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 3111 65535 0][var 0] points left...[n]We didn't make it. Was it my fault[n]for being too nervous...?[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 53539 65535 0]Hehe! It was so fun to play with[n]everyone! I didn't even realize how[n]into it I was![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_haru [Haru]]
[s][vp 8 2 0 3054 65535 0]Well, goodbye for now![n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Okay then, shall we? I'm all prepared[n]on my end.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8018 65535 0]Would you mind if I took the next game?[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]...Let's do one more.[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8028 65535 0]Really now... Well, that's fine.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules... Let's play 301.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules... Let's play 501.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Which ruleset should we use...?[n]All right, I'll leave it up to you.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_akech [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]All right, let's play 701. I trust you[n]don't have a problem with that?[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8128 65535 0]You can go first.[n][f 1 3 65535][w][e]

[msg MSG_StartRound02_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54447 65535 0]So I'm up next.[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Now it's your turn. Things are getting[n]interesting.[n][f 1 3 65535][w][e]

[msg MSG_StartRound04_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]So this will be my final round...[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8153 65535 0]Well, it's all up to you now. Best of[n]luck to you.[n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_akec [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8047 65535 0]...That's unfortunate. Don't let it[n]bother you though.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_akechi [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8044 65535 0]...It seems I'm a bit off my game.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8128 65535 0]All right, time to finish this. Oh, do you[n]have some words of encouragement[n]for me?[n][f 1 3 65535][w][e]

[sel SEL_Finish_akechi top]
[s]I'm cheering on the inside.[e]
[s]You don't need any.[e]
[s]Go, go, Goro-saaan![e]

[msg MSG_Finish_Act01_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8048 65535 0]*chuckle* Is that a challenge? Very well,[n]I shall answer your lofty expectations.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_akechi [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8108 65535 0]I appreciate it. I tend to get distracted[n]if it's too loud.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54411 65535 0]Oh, sure... thanks.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_8 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8162 65535 0]That's a finish at 0 points.[n]Playing darts in a pair isn't so bad.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]It kills me to admit it... but that was a bit[n]exciting. Well, it's not a bad feeling.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_a_2 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8162 65535 0]That's a finish at 0 points.[n]Playing darts in a pair isn't so bad.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ak [Akechi]]
[s][bup 0 9 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0][var 0] left... We came up[n]just a bit short.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_8 [Akechi]]
[s][bup 0 9 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0][var 0] points left... We came up short.[n]I wonder what went wrong?[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54465 65535 0]Well, that was rather enjoyable.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_akechi [Akechi]]
[s][vp 8 2 0 8053 65535 0]Well then, see you later.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]Now then, let's get started. I'm ready[n]on my end.[n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_akechi_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54502 65535 0]I'm going next. Sound good?[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_akechiBlac [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0]...We're going again. You can't let it[n]end like this, can you?[n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_akechiBl [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54480 65535 0]What... Well, whatever.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_akechi_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules... Let's go with 301.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_akechi_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules... Let's go with 501.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_akechiBla [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Which ruleset should we use...?[n]All right, I'll leave it up to you.[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_akech_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Let's play 701. It'll be more fun that way.[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8128 65535 0]You can go first. I'm just going to[n]watch for now.[n][f 1 3 65535][w][e]

[msg MSG_StartRound02_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]So that's how you play... Hmph...[n]Watch and learn.[n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_akechiBl [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0]You're up now. You'd better focus.[n][f 1 3 65535][w][e]

[msg MSG_StartRound04_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54500 65535 0]So, I've reached my final round.[n]I'll pull this off without a hitch.[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_akechiBl [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54473 65535 0]This is the last round. Take your time.[n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_akec_2 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0]Hmph... You better not have done[n]that on purpose.[n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_akechiBl [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54488 65535 0]...Don't look at me like that.[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_9 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Hmm, it looks like I can finish it here...[n]Now, how to throw...[n][f 1 3 65535][w][e]

[sel SEL_Finish_akechiBlack top]
[s]It's up to you.[e]
[s]Like a detective?[e]
[s]You have to keep cool.[e]

[msg MSG_Finish_Act01_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54477 65535 0]Obviously. You didn't even need[n]to say it.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_akechiB [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54499 65535 0]I don't need you to tell me that.[n]I'm always calm.[n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_akechiB [Akechi]]
[s][bup 0 9 12 65535 0][f 4 10 65535 0 0][vp 8 2 0 54474 65535 0]What the hell does that even mean...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_9 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54475 65535 0]That finishes it, 0 points.[n]Not a bad result.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for your performance... Well,[n]I suppose you deserve some credit.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_a_3 [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54475 65535 0]That finishes it, 0 points.[n]Not a bad result.[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_ak_2 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54489 65535 0][var 0] left? Hmph...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_9 [Akechi]]
[s][bup 0 9 11 65535 0][f 4 10 65535 0 0][vp 8 2 0 54490 65535 0][var 0] points left...[n]Hmph. What a pathetic result.[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_akechiBlac [Akechi]]
[s][bup 0 9 10 65535 0][f 4 10 65535 0 0][vp 8 2 0 54501 65535 0]Well, I guess that served as a nice[n]distraction.[n][f 1 3 65535][w][e]

[msg MSG_DartsBye_akechiBlack [Akechi]]
[s][vp 8 2 0 54504 65535 0]I'll be going then.[n][f 1 3 65535][w][e]

[msg MSG_1stPlayOrder_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57033 65535 0][fName]-senpai, can we play a[n]match together? I think I'll throw[n]straighter if I'm teamed with you...![n][f 1 3 65535][w][e]

[msg MSG_NextPlayOrder_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57142 65535 0]Could I go next? Watching people[n]play really motivates me to join in.[n][f 1 3 65535][w][e]

[msg MSG_NextRetry_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57063 65535 0]...I'm sorry! L-Let's try that one more time![n][f 1 3 65535][w][e]

[msg MSG_OrderCancel_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57061 65535 0]I-I see...[n][f 1 3 65535][w][e]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]I understand, though. Let's play[n]next time![n][f 1 3 65535][w][e]

[msg MSG_CourseOnly301_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Shall we try 301? I think I should[n]be able to handle that.[n][f 1 3 65535][w][e]

[msg MSG_CourseOnly501_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]As for the rules...[n]Shall we try 501? If we work together,[n]I know we can clear this![n][f 1 3 65535][w][e]

[msg MSG_CourseFree_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Okay, which ruleset should we use...?[n]Sorry, could I ask you to choose?[n][f 1 3 65535][w][e]

[msg MSG_CourseFree_Fix_sumir [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Okay! Then we'll play [var 0].[n][f 1 3 65535][w][e]

[msg MSG_StartRound01_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57069 65535 0]You can do it! I'm cheering for you![n][f 1 3 65535][w][e]

[msg MSG_StartRound02_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57002 65535 0]Round 2... So it's my turn. I'll need[n]to watch my form when I throw![n][f 1 3 65535][w][e]

[msg MSG_Change_2to3_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57022 65535 0]We're just getting started! Be careful[n]not to lose focus![n][f 1 3 65535][w][e]

[msg MSG_StartRound04_sumire [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57064 65535 0]This is my last round! I have to make it count...[n][f 1 3 65535][w][e]

[msg MSG_Change_4to5_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57022 65535 0]This is the final round! I believe in[n]you, Senpai![n][f 1 3 65535][w][e]

[msg MSG_Change_HeroBust_sumi [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57163 65535 0]It's okay! You nailed it in spirit![n][f 1 3 65535][w][e]

[msg MSG_Change_Bust_sumire [Sumire]]
[s][bup 0 10 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 57042 65535 0]Oh, what happened there... I'm sorry.[n]My aim seems to be off...[n][f 1 3 65535][w][e]

[msg MSG_Chara_GetScore_finis_10 [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57048 65535 0]I can finish it...! But what would be[n]the best way to throw here?[n][f 1 3 65535][w][e]

[sel SEL_Finish_sumire top]
[s]Throw like a gymnast.[e]
[s]Don't think, just feel.[e]
[s]Trust your instincts.[e]

[msg MSG_Finish_Act01_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57116 65535 0]...You're right! I just have to believe[n]in myself![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act02_sumire [Sumire]]
[s][bup 0 10 2 65535 0][f 4 10 65535 0 0][vp 8 2 0 57119 65535 0]O-Okay...! Feel... I think I can do this![n][f 1 3 65535][w][e]

[msg MSG_Finish_Act03_sumire [Sumire]]
[s][bup 0 10 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 57170 65535 0]Wha...!? No, that doesn't make sense![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigGoo_10 [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57052 65535 0]Senpai! We got 0 points! Does that[n]mean we make an excellent team!?[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]Is it because we were perfectly synced...?[n]I feel so motivated right now![n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Good_s [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57052 65535 0]Senpai! We got 0 points! Does that[n]mean we make an excellent team!?[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_Bad_su [Sumire]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 57055 65535 0][var 0] left... That's unfortunate.[n]We just needed a bit more...[n][f 1 3 65535][w][e]

[msg MSG_BatonTouchGet_BigBad_10 [Sumire]]
[s][bup 0 10 5 65535 0][f 4 10 65535 0 0][vp 8 2 0 57055 65535 0][var 0] points left...[n]That's unfortunate. And it's all my fault...[n][f 1 3 65535][w][e]

[msg MSG_CoopPoint_sumire [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57162 65535 0]Thank you very much. I had a lot of fun![n][f 1 3 65535][w][e]

[msg MSG_DartsBye_sumire [Sumire]]
[s][vp 8 2 0 57071 65535 0]I hope we do this again sometime.[n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round01 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1188 65535 0]C'mon, you got this! Focus![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round02 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1156 65535 0]You're playing by yourself, so there's no[n]pressure. Just throw at your own pace![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round03 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1174 65535 0]All right, we're at the halfway point now.[n]Three rounds left. Keep at it![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round04 [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1175 65535 0]Two rounds to go! You gotta make[n]this one count![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_round05 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1106 65535 0]Last round, huh... Put everything you[n]got into those darts![n][f 1 3 65535][w][e]

[msg MSG_Solo_playing_BustAft [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 1182 65535 0]That was a mistake... But you've still[n]got a chance![n][f 1 3 65535][w][e]

[msg MSG_Solo_Clear [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 53140 65535 0]Finished with 0 points! I knew you[n]could do it![n][f 1 3 65535][w][e]

[msg MSG_Solo_NotClear_ScoreF [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 53139 65535 0]Hmm, couldn't beat it, huh? And you[n]were so close too...[n][f 1 3 65535][w][e]

[msg MSG_Solo_NotClear_ScoreB [Morgana]]
[s][bup 0 3 5 0 0][f 4 10 65535 0 0][vp 8 2 0 53141 65535 0]That didn't turn out so well...[n]But don't let it get you down, all right?[n][f 1 3 65535][w][e]

[msg MSG_Solo_ByeBye [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1049 65535 0]Okay, let's head back. We can go over[n]what's happened on the train![n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScoreQ_1st [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1019 65535 0]Oh yeah, how many points do you want[n]to start with? Looks like there's a few[n]different options.[n][f 1 3 65535][w][e]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 0 65535 0]301, 501, or 701... Seems like the difficulty[n]rises with the number, but that might also[n]make them more worth trying.[n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScoreQ_com [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 0 1019 65535 0]Oh right. How many points are you[n]gonna start with today?[n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScore_301 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1023 65535 0]Ah, 301, huh?[n]We should be able to take this one, easy![n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScore_501 [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1035 65535 0]Oh, 501, huh?[n]This oughta be a decent challenge.[n][f 1 3 65535][w][e]

[msg MSG_Solo_StartScore_701 [Morgana]]
[s][bup 0 3 2 0 0][f 4 10 65535 0 0][vp 8 2 0 1164 65535 0]Wow, you're starting at 701?[n]I'll do my best to cheer you on![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7048 65535 0]You're gonna miss if you tense up[n]like that. Just relax![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1181 65535 0]You guys are pretty good. I'm impressed.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6023 65535 0]You're all so good! I'd better not[n]fall behind![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Yusuk [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4020 65535 0]Precision is required, all the way down[n]to the fingertips... What depth this[n]game has.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Makot [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2048 65535 0]This is pretty challenging...[n]It makes me want to master it.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Futab [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9196 65535 0]Th-This atmosphere... C'mon, me,[n]I got this![n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3048 65535 0]Hehe! You're all so skilled.[n]I'd better keep up, too.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Akech [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0]Unused.[n][f 1 3 65535][w][e]

[msg MSG_DartsStartTalk_Yoshi [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57058 65535 0]What a mature atmosphere... This is fun![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Ryuji [Ryuji]]
[s][bup 0 2 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 7045 65535 0]Do it! We're rooting for ya![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Moru [Morgana]]
[s][bup 0 3 1 0 0][f 4 10 65535 0 0][vp 8 2 0 1045 65535 0]Stay calm! There's nothing we can't do![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Anne [Ann]]
[s][bup 0 4 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 6023 65535 0]Good luck! You can do it![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Yusuke [Yusuke]]
[s][bup 0 5 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 4045 65535 0]Now then, how will this turn out...?[n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Makoto [Makoto]]
[s][bup 0 6 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 2048 65535 0]Stay calm! Focus on your positioning.[n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Futaba [Futaba]]
[s][bup 0 8 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 9196 65535 0]Do it! Show us whatcha got![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Haru [Haru]]
[s][bup 0 7 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 3119 65535 0]You're okay! I know you can do this![n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Akechi [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8035 65535 0]Good luck.[n][f 1 3 65535][w][e]

[msg MSG_DartsYellTalk_Yoshiz [Sumire]]
[s][bup 0 10 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 57026 65535 0]Go for it! It's all about heart![n][f 1 3 65535][w][e]

[msg MND_chr_haiti]
[s][vp 8 2 0 0 65535 0]How many friends should I bring?[n][f 1 3 65535][w][e]

[sel SEL_chr_haiti_dbg top]
[s]Up to Ann (Default).[e]
[s]Up to Yusuke.[e]
[s]Up to Makoto.[e]
[s]Up to Futaba.[e]
[s]Up to Haru.[e]
[s]Up to Akechi.[e]
[s]Up to Sumire.[e]
[s]Start as is.[e]

[msg MND_InviteAndPosSet]
[s][vp 8 2 0 0 65535 0]Who was called?[n][f 1 3 65535][w][e]

[sel SEL_InviteAndPosSet top]
[s]Force settings[e]
[s]Do nothing[e]

[sel SELGEN_InviteAndPosSet top]
[s]Ryuji was called.[e]
[s]Morgana was called.[e]
[s]Ann was called.[e]
[s]Yusuke was called.[e]
[s]Makoto was called.[e]
[s]Haru was called.[e]
[s]Futaba was called.[e]
[s]Akechi was called.[e]
[s]Sumire was called.[e]
[s]Play alone.[e]

[msg MSG_DUMMY]
[s][vp 8 2 0 0 65535 0]Test[n][f 1 3 65535][w][e]

[msg MSG_DUMMY01]
[s][vp 8 2 0 0 65535 0]For a rematch, select if you play with the second person and what mode to play in.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY02]
[s][vp 8 2 0 0 65535 0]If you have max rank with the other person, choose the mode at this time.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY03]
[s][vp 8 2 0 0 65535 0]Refresh the score on the display.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY04]
[s][vp 8 2 0 0 65535 0]Switch display to "Mode Select status".[n][f 1 3 65535][w][e]

[msg MSG_DUMMY05]
[s][vp 8 2 0 0 65535 0]Set the partner's position at the counter.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY06]
[s][vp 8 2 0 0 65535 0]Switch the display mode to "Game status"[n][f 1 3 65535][w][e]

[msg MSG_DUMMY07]
[s][vp 8 2 0 0 65535 0]Finish Mode test[n][f 1 3 65535][w][e]
[s]When remaining points are below 60,[n]activate conversations for Finish.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ScoreSet]
[s][vp 8 2 0 0 65535 0]Set the starting score for this game.[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ChallengeScore]
[s][vp 8 2 0 0 65535 0]The challenge score for Game 1 is [var 0].[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ChallengeScore_2]
[s][vp 8 2 0 0 65535 0]The challenge score for Game 2 is [var 0].[n][f 1 3 65535][w][e]

[msg MSG_DUMMY_ChallengeScore_3]
[s][vp 8 2 0 0 65535 0]The challenge score for Game 3 is [var 0].[n][f 1 3 65535][w][e]

[msg MSG_DBG_DebugMsgOpen]
[s][vp 8 2 0 0 65535 0]Display debug messages?[n][f 1 3 65535][w][e]

[sel SEL_DBG_MsgOpen top]
[s]No[e]
[s]Yes[e]

[msg MSG_DBG_ChallengeScore]
[s][vp 8 2 0 0 65535 0]Calculated Challenge Score this time is [var 10][n][f 1 3 65535][w][e]

